version: "3.9"

services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
    volumes:
      - ./vault/config:/vault/config
      - ./vault/data:/vault/data
      - ./vault/policies:/vault/policies
      - ./vault/scripts:/vault/scripts
    command: vault server -config=/vault/config/vault.hcl
